import {
    SiGit,
    SiJavascript,
    SiNextdotjs,
    SiPostgresql,
    SiReact,
    SiTailwindcss,
    SiTypescript,
    SiHtml5,
    SiCss3,
    SiNodedotjs,
    SiExpress,
    SiMongodb,
    SiMysql,
    SiAxios,
    SiFirebase,
    SiPython,
  } from "react-icons/si";
  
  export const skills = [
    { text: "React", Icon: SiReact },
    { text: "Next.js", Icon: SiNextdotjs },
    { text: "Tailwind", Icon: SiTailwindcss },
    { text: "PostgreSQL", Icon: SiPostgresql },
    { text: "Git", Icon: SiGit },
    { text: "Typescript", Icon: SiTypescript },
    { text: "Javascript", Icon: SiJavascript },
    { text: "HTML", Icon: SiHtml5 },
    { text: "CSS", Icon: SiCss3 },
    { text: "Node.js", Icon: SiNodedotjs },
    { text: "Express.js", Icon: SiExpress },
    { text: "MongoDB", Icon: SiMongodb },
    { text: "Axios", Icon: SiAxios },
    { text: "Firebase", Icon: SiFirebase },
    { text: "MySQL", Icon: SiMysql },
    { text: "Python", Icon: SiPython },
  ];